{% set name = "mouseinfo" %}
{% set version = "0.1.3" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/MouseInfo-{{ version }}.tar.gz
    sha256: 2c62fb8885062b8e520a3cce0a297c657adcc08c60952eb05bc8256ef6f7f6e7
    patches:
      # TODO: remove if/when upstream PR is merged
      - 000-python-xlib.patch
  # TODO: remove if/when upstream PR is merged
  - url: https://raw.githubusercontent.com/asweigart/mouseinfo/master/LICENSE.txt
    sha256: 8ceb4b9ee5adedde47b31e975c1d90c73ad27b6b165a1dcd80c7c545eb65b903

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python
  run:
    - pillow
    - pyobjc-core  # [osx]
    - pyperclip
    - python
    - python-xlib  # [linux]
    - rubicon-objc  # [osx]

test:
  imports:
    - mouseinfo  # [not linux]
  commands:
    - pip check
    - xvfb-run --server-args=":99 -screen 0 1024x768x24 -ac +extension GLX -noreset" python -c "import mouseinfo"
  requires:
    - pip

about:
  home: https://github.com/asweigart/mouseinfo
  summary: An application to display XY position and RGB color information for the pixel currently under the mouse. Works on Python 2 and 3.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
