{% set version = "0.9.0" %}

package:
  name: typing-inspect
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/typing-inspect/typing_inspect-{{ version }}.tar.gz
  sha256: b23fc42ff6f6ef6954e4852c1fb512cdd18dbea03134f91f856a95ccc9461f78

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - mypy_extensions >=0.3.0
    - python >=3.5
    - typing-extensions >=3.7.4

test:
  source_files:
    - test_typing_inspect.py
  requires:
    - pip
    - pytest
    - coverage
  imports:
    - typing_inspect
  commands:
    - pip check
    - coverage run --source=typing_inspect --branch -m pytest -vv --color=yes --tb=long test_typing_inspect.py
    - coverage report --show-missing --skip-covered --fail-under=25

about:
  home: https://github.com/ilevkivskyi/typing_inspect
  summary: Runtime inspection utilities for typing module.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
