{% set version = "0.10.2" %}

package:
  name: ssort
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/s/ssort/ssort-{{ version }}.tar.gz
    sha256: 58abef52533b62382d5d6b117b5416ba3fe709e96ef846ae9107aba202476587
  - folder: src
    url: https://github.com/bwhmather/ssort/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 44c9a1b77766e822da37bcaa94646f4682115a91c507bb7c28e5c8c84f77a5a4

build:
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - ssort = ssort._main:main

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  source_files:
    - src/tests
    - src/test_data
  imports:
    - ssort
  commands:
    - pip check
    - ssort --help
    - cd src && pytest -vv --cov ssort --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 94 -k "not no_new_module_builtins"
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/bwhmather/ssort
  summary: The python statement sorter
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
