{% set version = "2.2.1" %}

package:
  name: recurring-ical-events
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/r/recurring-ical-events/recurring_ical_events-{{ version }}.tar.gz
    sha256: ecfb9d97c39df31248de6fbc3abd7e226c9721bd7a7db525d9c8f90ce81f15c0
  - folder: src
    url: https://github.com/niccokunzmann/python-recurring-ical-events/archive/refs/tags/v{{ version }}.tar.gz
    sha256: f213ef0a60c39581c28f8b8157797bcdc1e09541146f7862b65df097bfce6a95

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - icalendar >=5.0.9
    - python >=3.7
    - python-dateutil >=2.8.1
    - pytz >=2023.3
    - x-wr-timezone <1.0.0

test:
  source_files:
    - src/test
    - src/README.rst
  imports:
    - recurring_ical_events
  commands:
    - pip check
    - cd src && coverage run --source=recurring_ical_events -m pytest -vv --tb=long --color=yes -k "not zoneinfo"
    - coverage report --show-missing --skip-covered --fail-under=94
  requires:
    - coverage
    - pip
    - pygments
    - pytest
    - restructuredtext_lint
    - tzdata

about:
  home: https://github.com/niccokunzmann/python-recurring-ical-events
  summary: A Python module which repeats ICalendar events by RRULE, RDATE and EXDATE.
  license: LGPL-3.0
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
