{% set name = "pygetwindow" %}
{% set version = "0.0.9" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyGetWindow-{{ version }}.tar.gz
    sha256: 17894355e7d2b305cd832d717708384017c1698a90ce24f6f7fbf0242dd0a688
  # TODO: remove if/when upstream PR is merged
  - url: https://raw.githubusercontent.com/asweigart/PyGetWindow/master/LICENSE.txt
    sha256: f8c2193c7e92df1a8335548a69653fa56b0ea3536586d93932f8c79c206df9fd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  skip: true  # [not win]

requirements:
  host:
    - pip
    - python
  run:
    - pyrect
    - python

test:
  imports:
    - pygetwindow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asweigart/pygetwindow
  summary: A simple, cross-platform module for obtaining GUI information on application's windows.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
