{% set version = "0.1.0" %}

package:
  name: notebook-shim
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/notebook-shim/notebook_shim-{{ version }}.tar.gz
  sha256: 7897e47a36d92248925a2143e3596f19c60597708f7bef50d81fcd31d7263e85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - jupyter-packaging >=0.9,<1
  run:
    - jupyter_server >=1.8,<2
    - python >=3.7

test:
  imports:
    - notebook_shim
  requires:
    - m2-grep  # [win]
    - pip
    - pytest
  commands:
    - pip check
    - jupyter server extension list
    - jupyter server extension list 1>server_extensions 2>&1
    - grep -iE "notebook_shim.*enabled" server_extensions
    - pytest --pyargs notebook_shim -vv


about:
  home: https://github.com/jupyter/notebook_shim
  summary: A shim layer for notebook traits and config
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - conda-forge/nbclassic
