{% set goname = "github.com/minio/mc" %}
{% set version = "2022-04-16T21-11-21Z" %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: minio-client
  version: {{ version.replace("-", ".").replace("T", ".").replace("Z", "") }}

source:
  - folder: {{ pkg_src }}
    url: https://github.com/{{ goname }}/archive/refs/tags/RELEASE.{{ version }}.tar.gz
    sha256: 94c1d0b2450b8024f70142ac15a1cddfe007779de9f52264d7e572f4ab6de801

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go install -v -ldflags "-X main.revision=conda-forge" .

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - mc --version

about:
  home: https://{{ goname }}
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file: {{ pkg_src }}/LICENSE
  summary: |-
    MinIO Client is a replacement for ls, cp, mkdir, diff and rsync commands for
    filesystems and object storage.

extra:
  recipe-maintainers:
    - bollwyvl
