{% set version = "0.1.1" %}

package:
  name: matplotlib-inline
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/matplotlib-inline/matplotlib-inline-{{ version }}.tar.gz
  sha256: eff59462c3d578b3488408e8f56da51715cf298500542738df0bc5a6500ec2c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - ipython
    - python >=3.5
    - traitlets

test:
  imports:
    - matplotlib_inline.backend_inline
  commands:
    - pip check
  requires:
    - pip
    - matplotlib-base

about:
  home: https://github.com/martinRenou/matplotlib-inline
  summary: Inline Matplotlib backend for Jupyter
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
