{% set version = "0.6.4" %}

package:
  name: winshell
  version: {{ version }}

source:
  url: https://github.com/tjguk/winshell/archive/refs/tags/{{ version }}.tar.gz
  sha256: 771223995d5d878e164e942c85d2fde9cce6f6cd502f52f677e4cdbc729c6087

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - pywin32

test:
  source_files:
    - test_base.py
    - test_winshell.py
    - test_winshell_25plus.py
    - testing_config.ini
  imports:
    - winshell
  commands:
    - pip check
    - coverage run --source=winshell --branch -m pytest --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under=100
  requires:
    - pip
    - pytest
    - coverage

about:
  home: https://github.com/tjguk/winshell
  summary: Windows shell functions
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://winshell.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
