{% set name = "rubicon-objc" %}
{% set version = "0.4.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rubicon-objc-{{ version }}.tar.gz
  sha256: a54be431be212c95106b3f9dbb3903fd96683caca926613ba7dd8b4605cb87cc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5

test:
  imports:
    - rubicon
    - rubicon.objc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://beeware.org/rubicon
  summary: A bridge between an Objective C runtime environment and Python.
  dev_url: https://github.com/beeware/rubicon-objc
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
