{% set name = "coursier" %}
{% set version = "2.0.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - fn: {{ name }}-{{ version }}-LICENSE-APACHE
    url: https://raw.githubusercontent.com/{{ name }}/{{ name }}/v{{ version }}/LICENSE
    sha256: cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30
  - url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}
    sha256: d3ba37e53d9cfa778af481c7099cd1dc485242283e9d2c5c2753f3859908cbd4

build:
  number: 0

requirements:
  build:
    - openjdk
  host:
    - openjdk

test:
  commands:
    - echo "TBD"

outputs:
  - name: {{ name }}-base
    requirements:
      build:
        - openjdk
    build:
      script: call "%RECIPE_DIR%\build_{{ name }}.bat"  # [win]
      script: bash "${RECIPE_DIR}/build_{{ name }}.sh"  # [unix]
    test:
      commands:
        - dir "%SCRIPTS%\{{ name }}.bat"  # [win]
        - ls "${PREFIX}/bin/{{ name }}"  # [unix]

  - name: {{ name }}
    requirements:
      run:
        - openjdk
        - {{ name }}-base ={{ version }}
    test:
      requirements:
        - openjdk
      commands:
        - java -version
        - {{ name }} --version
        - {{ name }} --help
    about:
      summary: Pure Scala Artifact Fetching (with conda JDK)

about:
  home: https://get-coursier.io
  license: Apache-2.0
  license_family: APACHE
  license_file: {{ name }}-{{ version }}-LICENSE-APACHE
  summary: Pure Scala Artifact Fetching
  doc_url: https://get-coursier.io/docs/overview
  dev_url: https://github.com/coursier/coursier

extra:
  recipe-maintainers:
    - bollwyvl
    - dbast
