{% set name = "coursier" %}
{% set version = "2.0.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://raw.githubusercontent.com/{{ name }}/{{ name }}/v{{ version }}/LICENSE
    sha256: cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30
  - url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}  # [unix]
    sha256: d3ba37e53d9cfa778af481c7099cd1dc485242283e9d2c5c2753f3859908cbd4  # [unix]
  - url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}.bat # [win]
    sha256: 843319e0a3c57e588a0dd25edd2fee4621ec9cd152741d3128a5f5366264a593  # [win]

build:
  number: 0

requirements:
  host:
    - openjdk
  run:
    - openjdk

test:
  commands:
    - coursier --version
    - coursier --help

about:
  home: https://get-coursier.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pure Scala Artifact Fetching
  doc_url: https://get-coursier.io/docs/overview
  dev_url: https://github.com/coursier/coursier

extra:
  recipe-maintainers:
    - bollwyvl
