{% set name = "chromium" %}
{% set version = "536395" %}
{% set cbs = "https://storage.googleapis.com/chromium-browser-snapshots" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ version }}.zip
  url: {{ cbs }}/Linux_x64/{{ version }}/chrome-linux.zip  # [linux]
  url: {{ cbs }}/Mac/{{ version }}/chrome-mac.zip  # [osx]
  url: {{ cbs }}/Win/{{ version }}/chrome-win32.zip  # [win32]
  url: {{ cbs }}/Win_64/{{ version }}/chrome-win32.zip  # [win64]

  sha256: 57e76dd588a7227ae78119937fe42ccd9f0c9da8f53f1d391e6b7bd90d751c14  # [linux]
  sha256: bd9d833376dfd46690666d2e16c630a6ba9cbf28e2a1b9b2c8c8abdecc211671  # [osx]
  sha256: 9a025817c31f2aa6ad29e46277f9dee6b32d5fe1d56aabb9b66a0548de2e461b  # [win32]
  sha256: 2d50ce6c935447ad896e221a1c9f3321cc503d59d834c00b5889dc769f243c2a  # [win64]

build:
  number: 0

requirements:
  build: []
  run: []

test:
  commands:
    - chrome --version --headless --disable-gpu  # [win]
    - chrome --version --headless  # [unix]

about:
  home: https://www.chromium.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: >
    Chromium is an open-source browser project that aims to build a safer,
    faster, and more stable way for all Internet users to experience the web.
  dev_url: https://chromium.googlesource.com/chromium/src/

extra:
  recipe-maintainers:
    - bollwyvl
