{% set name = "typer" %}
{% set version = "0.3.2" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typer-{{ version }}.tar.gz
  sha256: 5455d750122cff96745b0dec87368f56d023725a7ebc9d2e54dd23dc86816303

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - flit
    - pip
    - python >=3.6
  run:
    - click >=7.1.1,<7.2.0
    - python >=3.6

test:
  source_files:
    - tests
    - docs_src
    - README.md
    - pyproject.toml
  imports:
    - typer
  commands:
    - pip check
    - pytest -vv --cov typer --cov-fail-under 83 --cov-report term-missing:skip-covered
  requires:
    - coverage >=5.2,<6.0
    - pip
    - pytest >=4.4.0,<5.4.0
    - pytest-cov >=2.10.0,<3.0.0
    - shellingham >=1.3.0,<2.0.0

about:
  home: https://github.com/tiangolo/typer
  summary: Typer, build great CLIs. Easy to code. Based on Python type hints.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
