{% set name = "pyrect" %}
{% set version = "0.1.4" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyRect-{{ version }}.tar.gz
    sha256: 3b2fa7353ce32a11aa6b0a15495968d2a763423c8947ae248b92c037def4e202
  # TODO: remove when/if upstream PR is merged
  - url: https://raw.githubusercontent.com/asweigart/PyRect/master/LICENSE.txt
    sha256: acd22ce944f31780b1e3ffc67cea696421a7a582ad6abe5ef4d46ee9bb68aec9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - pyrect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asweigart/pyrect
  summary: PyRect is a simple module with a Rect class for Pygame-like rectangular areas.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
