{% set name = "neuralcoref-model" %}
{% set version = "4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: neuralcoref_cache/neuralcoref
    url: https://s3.amazonaws.com/models.huggingface.co/neuralcoref/neuralcoref.tar.gz
    sha256: e6140dc57e67e6f2978f21a645457066b1bb66b64f5b1f4949b1ffc7342e699d

build:
  noarch: generic
  number: 0
  script: cd {{ RECIPE_DIR }} && {{ PYTHON }} copy_model.py

requirements:
  build:
    - python >=3.6
  run:
    - neuralcoref ={{ version }}

test:
  requires:
    - python
  downstreams:
    - neuralcoref

about:
  home: https://huggingface.co/coref
  license: MIT
  license_family: MIT
  license_file: mit.txt
  summary: 'Pre-trained model for neuralcoref'
  dev_url: https://github.com/huggingface/neuralcoref

extra:
  recipe-maintainers:
    - bollwyvl
