{% set version = "300" %}
{% set build_number = 0 %}

package:
  name: pywin32-on-win
  version: {{ version }}

source:
  # just to get bot updates: we don't actually do anything with this
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: 7ce66b7c624c6ca083ed54d81d826ea95268f3e47ece4c811ac086dd9f15b542

build:
  noarch: python
  {% if build_script == 'noop' %}
  number: {{ build_number | int * 2 }}
  skip: true  # [win]
  {% elif build_script == 'on-windows' %}
  number: {{ build_number | int * 2 + 1 }}
  skip: true  # [not win]
  {% endif %}

requirements:
  host:
    - python >=2.7

  {% if build_script == 'noop' %}
  run_constrained:
    # an impossible-to-satisfy package, as the oldest available version is vc=8
    - vc <0
  {% endif %}

  run:
    - python >=2.7
    {% if build_script == 'on-windows' %}
    - pywin32 =={{ version }}
    {% endif %}

test:
  imports:
    - pywin32  # [win]
  commands:
    - echo "nothing to see here"  # [not win]

about:
  home: https://github.com/mhammond/pywin32
  license: PSF-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows (or nothing on UNIX)
  description: |
    A set of extension modules that provides access to many of the Windows API functions.

    Other packages may depend on this package if they wish to stay `noarch: python`
  dev_url: https://github.com/mhammond/pywin32

extra:
  recipe-maintainers:
    # TODO: ping upstream maintainers
    # - mingwandroid
    # - nicoddemus
    # - carlodri
    - bollwyvl
